version: '3.7'

services:
  db:
    image: postgres
    ports:
      - '5438:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather
      POSTGRES_USER: user
    volumes:
      - ./data:/var/lib/postgresql
      - ./pg-initdb.d:/docker-entrypoint-initdb.d

